{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.configName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mysql.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
{{- end }}
